DELETE http://localhost:5000/meetings/615516217b93b89e4d062761
Accept: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6IjYxNTQ0YzI0ODFmYjk1ZWU3MzAzNzEzYSIsImlhdCI6MTYzMzAwNzY1Mn0.ws5e1eohTySXqGYdpqBikkn-d68CwdIFK5U9xh8UAD4

###
POST http://localhost:5000/meetings
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpZCI6IjYxNTQ0YzI0ODFmYjk1ZWU3MzAzNzEzYSIsImlhdCI6MTYzMzAwNzY1Mn0.ws5e1eohTySXqGYdpqBikkn-d68CwdIFK5U9xh8UAD4

{
  "id": "615516217b93b89e4d062761",
  "title": "this is a test"
}

###
GET http://localhost:5000/meetings/
Accept: application/json

###


